// <auto-generated />
using System;
using AMSSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMSSystem.Migrations.SQLDbcontextMigrations
{
    [DbContext(typeof(SQLDbcontext))]
    [Migration("20251028111517_addedentity")]
    partial class addedentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMSSystem.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("BankId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", "Training");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AMSSystem.Models.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankType")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("BankId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BranchId");

                    b.ToTable("Banks", "Training");
                });

            modelBuilder.Entity("AMSSystem.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchPincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchId");

                    b.HasIndex("BankId");

                    b.ToTable("Branch", "Training");
                });

            modelBuilder.Entity("AMSSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dateofbirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("AccountId");

                    b.ToTable("Users", "Training");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AMSSystem.Models.Account+CurrentAccount", b =>
                {
                    b.HasBaseType("AMSSystem.Models.Account");

                    b.Property<decimal>("WithDrawAmount")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("CurrentAccounts", "Training");
                });

            modelBuilder.Entity("AMSSystem.Models.Account+FixedDepositAccount", b =>
                {
                    b.HasBaseType("AMSSystem.Models.Account");

                    b.Property<DateTime>("Maturitydate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RateofInterest")
                        .HasColumnType("int");

                    b.ToTable("FDAccount", "Training");
                });

            modelBuilder.Entity("AMSSystem.Models.Account+SavingsAccount", b =>
                {
                    b.HasBaseType("AMSSystem.Models.Account");

                    b.Property<decimal>("WithDrawAmount")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("SavingsAccount", "Training");
                });

            modelBuilder.Entity("AMSSystem.Models.User+BankUser", b =>
                {
                    b.HasBaseType("AMSSystem.Models.User");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BankUser", "Training");
                });

            modelBuilder.Entity("AMSSystem.Models.Account", b =>
                {
                    b.HasOne("AMSSystem.Models.Bank", "bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMSSystem.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bank");

                    b.Navigation("user");
                });

            modelBuilder.Entity("AMSSystem.Models.Bank", b =>
                {
                    b.HasOne("AMSSystem.Models.Account", null)
                        .WithMany("banks")
                        .HasForeignKey("AccountId");

                    b.HasOne("AMSSystem.Models.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");
                });

            modelBuilder.Entity("AMSSystem.Models.Branch", b =>
                {
                    b.HasOne("AMSSystem.Models.Bank", null)
                        .WithMany("Branches")
                        .HasForeignKey("BankId");
                });

            modelBuilder.Entity("AMSSystem.Models.User", b =>
                {
                    b.HasOne("AMSSystem.Models.Account", null)
                        .WithMany("users")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("AMSSystem.Models.Account+CurrentAccount", b =>
                {
                    b.HasOne("AMSSystem.Models.Account", null)
                        .WithOne()
                        .HasForeignKey("AMSSystem.Models.Account+CurrentAccount", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMSSystem.Models.Account+FixedDepositAccount", b =>
                {
                    b.HasOne("AMSSystem.Models.Account", null)
                        .WithOne()
                        .HasForeignKey("AMSSystem.Models.Account+FixedDepositAccount", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMSSystem.Models.Account+SavingsAccount", b =>
                {
                    b.HasOne("AMSSystem.Models.Account", null)
                        .WithOne()
                        .HasForeignKey("AMSSystem.Models.Account+SavingsAccount", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMSSystem.Models.User+BankUser", b =>
                {
                    b.HasOne("AMSSystem.Models.User", null)
                        .WithOne()
                        .HasForeignKey("AMSSystem.Models.User+BankUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMSSystem.Models.Account", b =>
                {
                    b.Navigation("banks");

                    b.Navigation("users");
                });

            modelBuilder.Entity("AMSSystem.Models.Bank", b =>
                {
                    b.Navigation("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
